---

git_repo: git@github.com:paolopaolopaolo/dance_dance_tacoparty.git
repo_name: dance_dance_tacoparty

project_name: dance_dance_tacoparty
application_name: dance_dance_tacoparty

git_ssh_pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzs2DN/n7NhjD3ZEUHz8j8lgbhpa34x/uXReGt/TVtIla54WSd4Y+zJ8cbQuZ87kMri7clexTZmoh3ZnT8GMKpWHyNPCGx2DA41K5lmhnoni0y7KsIB9TndkgX0pnh4QI12V1z5vLNlDZKo2q1UW+cHUND6+Z2bbt9Qr7vKlA4QVFZmCh7X/DbifqyDi17tx4N/lhM+XTVw9V1LRpvxENKVIONyb7pwujfs5QcWaGTYoitHdEkylu0bioH8kjDcESRrKXxIMAsGgBlpFGG0WlittjCvy7WGrpZjJJoGJZTHw+mgV5FlIEAWSwu6Xg6iqbpsoJYslZgjyOGj37sqnvi757OKTMd1gahTdnDQhTm/GMXC4WPBwyPBxlFma6UITStM/tXxJM60JuKyP0ns2EGWFcn56drhnyvijnwATopb/Bby1EE3srcNTQmo1bMhUQcrWciQyj8P4tP9ThC/7XdM/+OVFAfALlHrRmvhAlLJjSnOB/fbihN2lCBjhmC0s3Sl1Qf5NPlGHuwrelRDpwAawffoyZhWoWTjxFO9LkbiHoB7ctqrlANKWwA44wpp74YXiagky9qlZFjK4qQMeLj8cbxMQv57x2/biPbBYRlzzfO4QVgbS1bXLjTLB7xkXRkEdIhLLn695FNPr9U/JnqlVUdnYdZ9ZM8f/u+wfzVKQ==
git_ssh_priv_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEAs7Ngzf5+zYYw92RFB8/I/JYG4aWt+Mf7l0Xhrf01bSJWueFk
  neGPsyfHG0LmfO5DK4u3JXsU2ZqId2Z0/BjCqVh8jTwhsdgwONSuZZoZ6J4tMuyr
  CAfU53ZIF9KZ4eECNdldc+byzZQ2SqNqtVFvnB1DQ+vmdm27fUK+7ypQOEFRWZgo
  e1/w24n6sg4te7ceDf5YTPl01cPVdS0ab8RDSlSDjcm+6cLo37OUHFmhk2KIrR3R
  JMpbtG4qB/JIw3BEkayl8SDALBoAZaRRhtFpYrbYwr8u1hq6WYySaBiWUx8PpoFe
  RZSBAFksLul4Ooqm6bKCWLJWYI8jho9+7Kp74u+ezikzHdYGoU3Zw0IU5vxjFwuF
  jwcMjwcZRZmulCE0rTP7V8STOtCbisj9J7NhBlhXJ+ena4Z8r4o58AE6KW/wW8tR
  BN7K3DU0JqNWzIVEHK1nIkMo/D+LT/U4Qv+13TP/jlRQHwC5R60Zr4QJSyY0pzgf
  324oTdpQgY4ZgtLN0pdUH+TT5Rh7sK3pUQ6cAGsH36MmYVqFk48RTvS5G4h6Ae3L
  aq5QDSlsAOOMKae+GF4moJMvapWRYyuKkDHi4/HG8TEL+e8dv24j2wWEZc83zuEF
  YG0tW1y40ywe8ZF0ZBHSISy5+veRTT6/VPyZ6pVVHZ2HWfWTPH/7vsH81SkCAwEA
  AQKCAgAM7l+M8z9Uss9bPg/pm/4uju0316BJQrrMC+9NgecST2JGRf3jjpO0pKwj
  PhEv9EVJIOiw/cZmUkR3sxu/+Fgpr4Bm+WjDT3dI36UdEpXCs381Juq3zTh4334Y
  mMMSCgsKrPWYnYnjWUL+4/uNyKprZX+tp5AR/Zt8TA1JUJYtNiYQeG6RUjoW0jsE
  DRkgyfCTuTXJdDoAF/OIVxKL8GeXNbWxwk7Gq4vubRG/aIPEA1cqffbK2vT2aucD
  Y1/xEGcexHm8fErX4ZcduVFUjkUzIU0/1locdhfq0b7HVt2aZaXOqYiLIUCXMdOI
  HKzWKZwRPRM8JrkogaRgznqntSzs7L2NGc8pBpHBflxa1wLpaCi+jPphWcvfEyRk
  w54UBsUk1eZbDSCFIdC8POTvDpigaBqNBhS9aeY8q759pe89r/6Xr+iqR/97ua6e
  N4/Zw8ywO21PUi9YSw11K95UkMpfl2QGHCmggtl1KwfPcmiRjXC+fP0Vc5SKOZ9N
  xdtqL704S+t7qNbdsLVig+YdkSMzhlNKbj2MT4h2Hij/wb7Fz5uwtT05lnzMsIX9
  gXqAhIfYkugA9OpM27yi2uZWRMjKlrqI33Enfm6tqyvdI7FcmU91/zenPOIhNmla
  a1pnz0BTGmrmjNonCznpuOpvuG5y2zjXGuz7eHw2FjtXLtoMAQKCAQEAylurKL7n
  jXVimDUMfgHm/pM3k/pWSclnJnrMeNXLSoTxCfaNmFraOYG7pHoHqWZd/zWUniQ7
  dvKOdsOQJKo3nat4sXTbiLjvPFQHLW3AbNBY7/KplAQMfHHm9OBfykF6fveU4pyD
  Cc31pCFj82cWdjgzUmgyDZ2W/1ejsHdwFS8B1dndETEvZh9CzJE2VDwfvSeIqCrN
  iXC22elkkLA2a37FFRKp+Tue+KjsXdiOPfQB/IYrBABrw0piaZUfxu8a1v36Bod3
  PiJVKMoGEKjTIXMCaNlmbdMl8GfZA79TuVQJw0TH3H8IwEOTyPzZOnmWGEC+9Ew/
  tn1f0SUlAea7IQKCAQEA41Yk/Z33APrErKP/UqK4K7o6yVo9gbOVXbdy1LIndm7V
  Z0tOb1ZvqaxDOGzDWT/6KvA5k60fMrvuKMl1/G6+Zv13s5I3oYldKrBb7CK7jt+t
  lhH1/1a+ICeC/D6tMLw8ZV057C3RkhAD1zF73X93dJWJFRNkYmNQr3ZnB+jbM1a5
  rYNnSZ5yaJYC+yYVjrBl6oVR5zmJ/K7v4+MyjBErjV/4ZjAFxXPL65F2sf8Poco+
  nmSJs+te5ptTuktcRagKRUg6JyaMs6/Y6I1Gios3xaZwCt09tsFzRtSDyCOEIfHC
  Ki6gVFFRB0Pm54djgDeaGP9mDmkBMkqz8koJ46EhCQKCAQA+w3Xv+l5Jcto0yWdp
  gd+KoFDBtgijdDNpLPdUl0MphthYNb+vPKao5YM0vaC4uwZ2jMDe1/AVsZ/cWEXS
  CXWckr2plMwuuOWC+bEMNxlS5sBfFA3i2eqhgpaW5yzux6Zd0R69truyA86nrK+a
  pCPEYSQR8D1uGa3m3uDnb/Q0rdLM6Hj3xyCjdRi76GJIeCmD+soZFsWPVoVwS0Kk
  2fLXHoe0RIixw/tHtuUxKmTb9F3VXCvlXtgNx3mEs/saMblKa5XsBoJGpFFziE2f
  Ry3NFyXtLVjmwXHoAd2+ms42EknA5glza3dkYtFoqnwZ9fJG7XYMwcWVLYfVj8bN
  synhAoIBAHT46TWZ5vMZFMNj6sbhNPRC8WaTSRyIg61h6/Lm7AkzRBjPFb+R8QiT
  u064H9e3ZIhdbLLAnFHlgsh3yH6nmM6zUrkR3g/+9vI1JkcdI/aCvvV9rl7AijlP
  O0WBFmoCIO1jB5+vf6qxFNjP/FTe9l8FZjBy9u7s/SIbQS4/sTH8SLOv7iBiJ6oK
  reP+F4+A0h/Wk2rvH0Hl3UcbqvGJECjBHbWutfl/+IfwI+u4Opnbz1Z+kqAB1qW/
  fFhZ2FN7ADXf0RQ98J2wOGKH9qjoszy+w93DMrLrXN4wENKU+7LfizFbJmHcKV4c
  oR22ewsJEQAVwbRecSAoceiUEfyO9skCggEBAKwDuj4ZoKRZVfr6idDCM0iQTISJ
  PtrfSquBkLAMExqrJEzDfzPFLAJOoTlikDpaQpN6z85T+S3QXjGW2prYS1t73qki
  +aBqZ/UypWB5v9mScstM695fmjrh8zcxxnjEclAdmECI07jo/OWIwZaRC2Nb7u+m
  hCz0DGBWdhxGMUx8Dq+8r1eGA6nZPap0AQvL2CYcotKlcvs2mXq3DSoUbu0jt6V3
  AIhD/FXl7OSZC9FEMpcwv5kMVF/ijlVOV575sO0ITZHk384KduXZK+0jmm4xWxJz
  cKPZYHGiWYpDhsvyEkznvLaoEaxvVYAnMdc4KTdbidZoXZZ1LdUmaBJv0+Q=
  -----END RSA PRIVATE KEY-----

